package com.learning.leap.bwb.utility;


public class Constant {
    public static final String CognitoIdentityPoolId = "us-east-1:43044b2f-5335-448c-a61f-f334d476c6ee";
    public static final String NOTIFICATION_MAX_TIME = "notificationMaxTime";
    public static final String NOTIFICATION_MIN_TIME = "notificationMinTime";
    public static final String BABBLE_ID = "babbleID";
    public static final String BABY_NAME = "babyName";
    public static final String ZIP_CODE = "zipCode";
    public static final String BABY_BIRTHDAY = "babyBirthDay";
    public static final String LAST_DAY_TURNED_OFF = "lastDayTurnedOff";
    public static final String DID_DOWNLOAD = "Did_Download";
    public static final String DID_UPDATE_TO_2 = "DID_UPDATE_TO+2";
    public static final String START_TIME = "START_TIME";
    public static final String END_TIME = "END_TIME";
    public static final String ALL_TIME_END_TIME = "ALL_TIME_END_TIME";
    public static final String SEND_TIPS_TODAY = "SEND_TIPS_TODAY";
    public static final String VIEWED_SETTINGS = "ViewedSettings";
    public static final String CHANGE_PROFILE_SETTINGS = "ChangeProfileSettings";
    public static final String CHANGED_NOTIFICATION_SETTINGS = "ChangedNotificationSettings";
    public static final String TURNED_OFF_NOTIFICATIONS_FOR_DAY = "TurnedOffNotificationsForDay";
    public static final String ACCESSED_APP = "AccessedApp";
    public static final String VIEWED_NOTIFICATIONS = "ViewedNotifications";
    public static final String PLAYED_VIDEO = "PlayedVideo";
    public static final String PLAYED_SOUND = "PlayedSound";
    public static final String VIEWED_PLAY_TODAY = "ViewedPlayToday";
    public static final String VIEWED_LIBRARY = "ViewedLibrary";
    public static final String VIEWED_VIDEOS = "ViewedVideos";
    public static final String VIEWED_BY_AGES = "ViewedByAges";
    public static final String VIEWED_BY_SETTINGS = "ViewedBySettings";
    public static final String NOT_NOW_CLICKED = "NotNowClicked";
    public static final String OK_CLICKED = "OKClicked";
    public static final String THUMBS_UP = "ThumbsUp";
    public static final String THUMBS_DOWN = "ThumbsDown";
    public static final String NUM_OF_TIPS = "NumberOfTips";
    public static final String NUM_OF_TIPS_INDEX = "NumberOfTipsIndex";
    public static final String UPDATE = "UPDATE";
    public static final String BWB = "Beginning With Babble";
    public static final String USER_BDAY_IN_MONTH = "USER_BDAY_IN_MONTH";
    public static final String GENDER = "GENDER";
    public static final String NEW_USER = "newUser";
    public static final String TIP_SCHEUDLED_TIME = "TIP_SCHUEDLED_TIME";
    public static final String NOTIFICATION_SIZE = "notficationListSize";
    public static final String TIP_ID = "TIP_ID";
    public static final String SAVED_BABY_AGE = "SAVED_BABY_AGE";
    public static final String I_WILL_LATER = "IWillLater";
    public static final String YES = "Yes";
    public static final String NO = "No";
    public static final String UpdatedScheduleBuckets = "UPDATED_SCHEDULE_BUCKETS";
    public static final String UpdatedTOPLAYTODAYJOB = "UPDATED_PLAY_TODAY_JOB";
}
